### PR TITLE
auth-policy: hashed_password will always be blank, tell buffer it has…

### PR DESCRIPTION
**Pull request by bearggg**
… data so str_len works when converting to hex

### CODE REVIEW

**Comment by cmouse** [comment]
Um. Those two are the same thing.

**Comment by bearggg** [comment]
It does look like it, however the str->used is zero at that point, so when str_truncate runs the if statement doesnt actually run buffer_set_used_size.

```
/* Truncate the string to specified length. If it's already smaller,
   do nothing. */
static inline void str_truncate(string_t *str, size_t len)
{
    if (str_len(str) > len)
        buffer_set_used_size(str, len);
}
```
Possibly the issue is further up the stack, but I dont see anything here that sets str->used? I didnt look to closely at digest->result as its just a pointer going in.
```
    ptr = (unsigned char*)str_c_modifiable(buffer);
    digest->result(ctx, ptr);
```
either way, str_len(buffer) is always zero for me, so the password word hash is always blank.  The proposed change seems to fix it and still appears safe.

**Comment by sirainen** [comment]
Oh, this was somewhat recently broken by e0e555a09a8ff93aa904586aeffd37f5b0e3a84d. But yeah, the buffer there isn't really a string so it would be even cleaner to have it be buffer_t instead of string_t.

**Comment by cmouse** [comment]
Opened internally, thanks.

**Pull request closed without merging**
