### PR TITLE
Update mbox-storage.c

### PR DESCRIPTION
**Pull request by AnneBennett**
Check mailbox access using effective UID instead of real uid.

### CODE REVIEW

**Comment by cmouse** [comment]
Hi, can you please try this https://cmouse.fi/0001-lib-storage-Use-faccessat-instead-of-access.patch and see if it works instead?

**Comment by AnneBennett** [comment]
> Hi, can you please try this
> https://cmouse.fi/0001-lib-storage-Use-faccessat-instead-of-access.patch
> and see if it works instead?

I'm not at work for the rest of the week, but sure, will do, next week.



Anne.

**Comment by AnneBennett** [comment]
> Hi, can you please try this
> https://cmouse.fi/0001-lib-storage-Use-faccessat-instead-of-access.patch
> and see if it works instead?

No it doesn't:

  Nov 29 11:25:43 lust dovecot: lmtp(anne)<18420><uC3+Lwf/pGH0RwAAs/mAJw>: Debug: lmtp-server: conn unix:pid=18419,uid=89 [2]: rcpt ***@***.***: Mailbox INBOX: Mailbox opened because: lib-lda delivery
  Nov 29 11:25:43 lust dovecot: lmtp(anne)<18420><uC3+Lwf/pGH0RwAAs/mAJw>: ***@***.***>: save failed to INBOX: Read-only mbox
  Nov 29 11:25:43 lust dovecot: lmtp(18420): Disconnect from local: Logged out (state=READY)
  Nov 29 11:25:43 lust postfix/lmtp[18419]: EC43F20067: ***@***.***>, relay=lust.encs.concordia.ca[/var/spool/postfix/private/dovecot-lmtp], delay=1196, delays=1196/0/0/0.01, dsn=4.2.0, status=deferred (host lust.encs.concordia.ca[/var/spool/postfix/private/dovecot-lmtp] said: 451 4.2.0 ***@***.***> Read-only mbox (in reply to end of DATA command))

... but now I've noticed your subsequent message suggesting
a different patch, so I'll try that one next.


Anne.
-- 
Ms. Anne Bennett, Senior Sysadmin, ENCS, Concordia University, Montreal H3G 1M8
***@***.***                                    +1 514 848-2424 x2285

**Comment by cmouse** [comment]
Hi Anne, we are doing this code differently at some point.

**Comment by sirainen** [comment]
So, idea is to use faccessat(). Jira: DOP-2673

**Pull request closed without merging**
