### PR TITLE
net: OpenBSD similar with FreeBSD at net_connect_ip_full

### PR DESCRIPTION
**Pull request by catap**

### CODE REVIEW

**Comment by cmouse** [comment]
Thanks, I'll put this forward

**Comment by catap** [comment]
@cmouse this is against release-2.3 branch, not main.

**Comment by cmouse** [comment]
oh, well, we fix things against main always.

**Comment by cmouse** [comment]
fixed with https://github.com/dovecot/core/compare/98220b678b6137d5b0a49fd0a5fb019fb2de64c8...6f6dc7c1c4d08f0f197b758c4ba8919aad640ada

**Pull request closed without merging**
