### PR TITLE
Execute /etc/sysconfig/dovecot on init, if it exists

### PR DESCRIPTION
**Pull request by tomsommer**
Helps users set `ulimit`, `DAEMON` etc. without having to touch the init.d script.

### CODE REVIEW

**Comment by cmouse** [comment]
This is pretty redhat-specific change, in debian the correct folder would be /etc/default/dovecot

**Comment by tomsommer** [comment]
You want a debian entry as well?

**Comment by donmichelangelo** [comment]
Isn't this something that should be left to the official package maintainers of the corresponding distributions? I mean this is pretty much contradicting to the philosophy of such binary distributions like CentOS (actually also Debian and others) if you install Dovecot straight from the source.

Ok, it's not forbidden, but it doesn't make much sense to be honest, especially if you can use the Fedora src rpm balls to compile newer Dovecot versions for RHEL 6/7 targets.

**Comment by tomsommer** [comment]
Well, some of us compile from source and copy the bundled init script in - that's why it's there?

**Comment by cmouse** [comment]
In internal review

**Comment by sirainen** [comment]
Could have been both in the same commit, but merged anyway.

**Pull request closed without merging**
