### PR TITLE
Update solr-config-9.xml

### PR DESCRIPTION
**Pull request by cyclops1982**
I had to make this change to make this work :)

### CODE REVIEW

**Comment by cmouse** [comment]
All of that?

**Comment by cyclops1982** [comment]
@cmouse  Not sure why the file changes look so strange, but look at the original file in main, you'll see 
```
root@cypher:~# cat /var/solr/data/dovecot/conf/solrconfig.xml
```
on line 204. I had to delete everything up to that line to get it to work.

**Comment by cmouse** [comment]
Oh fun. How did that ever pass ci

**Comment by cyclops1982** [comment]
I don't think CI does a full run of apache solr :-)

**Comment by cmouse** [comment]
But it does. Have to check..

**Comment by cmouse** [comment]
merged as 3294f9074a1c6f2b64f956a21dea3b8b51b33aaf

**Pull request closed without merging**
