### PR TITLE
Support a SASL mechanism filter

### PR DESCRIPTION
**Pull request by minfrin**
Adds a new filter to specify configuration by SASL mechanism.

### CODE REVIEW

**Comment by cmouse** [comment]
There is already mechanisms filter for passdbs. See https://doc.dovecot.org/configuration_manual/authentication/password_databases_passdb/#passdb-setting

**Comment by minfrin** [comment]
> There is already mechanisms filter for passdbs. See https://doc.dovecot.org/configuration_manual/authentication/password_databases_passdb/#passdb-setting

Alas passdbs isn't enough.

To support external and plain at the same time, plain needs "auth_ssl_username_from_cert = no", while external needs "auth_ssl_username_from_cert = yes".

This doesn't appear to be possible in passdb.

**Comment by sirainen** [comment]
Is that a problem though? With PLAIN authentication the client typically wouldn't present SSL certificate, which makes auth_ssl_require_client_cert irrelevant. And if a valid SSL certificate is presented with PLAIN, it should have the correct username anyway then?

**Comment by cmouse** [comment]
Does not really seem that useful, sorry.

**Comment by minfrin** [comment]
> Does not really seem that useful, sorry.

I've been caught up in other things, will give this another try to make work when I have more time.

**Pull request closed without merging**
