### PR TITLE
update_load_ca

### PR DESCRIPTION
**Pull request by huckabeec**
load_ca changes split out from other pull request #66

### CODE REVIEW

**Comment by cmouse** [comment]
The commit message is bit undescriptive, and still, this contains *two* changes in one commit. First fix how CA's are loaded, then add the ca_hash feature. Also this should compile with openssl 1.0.1, not sure where ca hash directory has been added.

**Comment by cmouse** [comment]
Also, it would be nice if the commit messages would be something like

lib-ssl-iostream: Description of change.

**Comment by huckabeec** [comment]
See if you like this better.  I'll move the other bits into the other pull request.

**Comment by huckabeec** [comment]
Would like to know if this can be reviewed again for acceptance to let me know if it still needs more changes.

**Comment by huckabeec** [comment]
Actually I need to look at this again, I was back porting to 2.2.35 and trying to think on how to split this up better from #70

**Comment by cmouse** [comment]
I think we have already fixed this in 2.3.14.

**Pull request closed without merging**
