### PR TITLE
Add UTF8 LMTP server support

### PR DESCRIPTION
**Pull request by VanVan**
Related links :
https://unix.stackexchange.com/questions/320091/configure-postfix-and-dovecot-lmtp-to-receive-mail-via-smtputf8
https://github.com/docker-mailserver/docker-mailserver/issues/1117

### CODE REVIEW

**Comment by cmouse** [comment]
Hi! Thank you for your pull request. We don't actually use this file for tracking work, and smtputf8 is on our list already.

**Comment by ElhananFine** [comment]
Hello cmouse.
We'd love for you to consider adding SMTPUTF8 support. This will allow me to create an email in my native language.
I'm using TLD ".ישראל", Postfix supports smtputf8, but I need to disable it because of Dovecot LMTP
Thank you for reading, Elhanan.

**Comment by leonklingele** [comment]
I'm very interested in this as well! Is there some issue I can follow, @cmouse ?

**Comment by cmouse** [comment]
Hi, this is a closed ticket, so we usually do not monitor these anymore. This feature is being considered, but unfortunately we do not have a public issue tracker at this time.

**Comment by phorcys420** [comment]
> Hi, this is a closed ticket, so we usually do not monitor these anymore. This feature is being considered, but unfortunately we do not have a public issue tracker at this time.

Bummer, could you link us to an issue tracker if you ever set one up (or give updates) ? (@cmouse)

I would really like for this feature to be implemented and for it to not die without me knowing.

Thanks !
Dovecot has been a great tool to work with.

**Pull request closed without merging**
