### PR TITLE
fix tests for alpine linux as socket name too long

### PR DESCRIPTION
**Pull request by a16bitsysop**

### CODE REVIEW

**Comment by cmouse** [comment]
Sorry for taking so long. Why is this an issue?

**Comment by a16bitsysop** [comment]
The current maintainer in alpine has a 3 letter name, if for example I submit a patch it will fail as my name is more than three characters which pushes it over the pathname limit.

**Comment by cmouse** [comment]
Isn't max pathlen in alpine linux 4096? How long paths are you guys using?

**Comment by cmouse** [comment]
Also to me this looks lot more like alpine linux maintainer problem, than dovecot problem. Fixing it like this will only cause it to break again.

**Comment by a16bitsysop** [comment]
I am not sure of the specific length, I can run it through the CI later to get the error message again.  The test path was very long.

**Comment by a16bitsysop** [comment]
Here is the error again:
https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/489469#L6518

**Comment by cmouse** [comment]
ok, we'll discuss what do to with this.

**Comment by a16bitsysop** [comment]
Thanks

**Comment by sirainen** [comment]
Merged https://github.com/dovecot/core/commit/9a3e0d099044d3a7478c3a24ccb8990181767f7c

**Pull request closed without merging**
