### PR TITLE
Allow setting TLSv1.3 as minimum TLS version

### PR DESCRIPTION
**Pull request by darix**

### CODE REVIEW

**Comment by egberts** [comment]
Ummmm, I have an operational need to disable TLSv1.3.  But there is no way for me to specify the following scenario.

```
ssl_min_protocol = TLSv1.2
ssl_max_protocol = TLSv1.2
```

Why was the decision made to change from `ssl_protocol` to `ssl_min_protocol`?

**Comment by darix** [comment]
Please open a separate issue about this

**Comment by egberts** [comment]
where's the Issues tab on this project page?

**Comment by cmouse** [comment]
We track issues internally. Send mail to dovecot@dovecot.org

**Comment by cmouse** [comment]
Fixed via 585e09f4d7b1788f45c0b88ed729758ee56c5980

**Pull request closed without merging**
