### PR TITLE
Add support for updating dictionary entries stored in Postgresql

### PR DESCRIPTION
**Pull request by geirp**
ON CONFLICT (...) DO UPDATE SET ... added to SQL-statement. 

The pgsql trigger mentioned on https://wiki2.dovecot.org/Quota/Dict is no longer needed.

### CODE REVIEW

**Comment by cmouse** [comment]
Since which postgres version is this?

**Comment by geirp** [comment]
This was added in Postgresql 9.5 which was released 2016-01-07.

https://www.postgresql.org/docs/9.5/release-9-5.html

Current release is 11.1.

9.4 is the oldest still supported release and will be supported until February 13, 2020.

https://www.postgresql.org/support/versioning/

**Comment by slavkoja** [comment]
BTW, SQLite has the same syntax supported from 3.24.0 (2018-06-04)

**Comment by cmouse** [comment]
Done as 5329cd3af4a459d12d7710fd1d42fb9a93bd6fe5

**Pull request closed without merging**
